### ISSUE TITLE
uploading trained ANN

### ISSUE THREAD

**Issue by jerabaul29** [thw1021/Cylinder2DFlowControlGeneral#2]
Hi @thw1021 ,

Could you upload the trained ANN, similarly to what is done here for example: https://github.com/jerabaul29/Cylinder2DFlowControlDRL/tree/master/Cylinder2DFlowControlWithRL/ANN_controlled_flow_singlerun ? :)

**Comment by jerabaul29** [comment]
(I know some people who may need it).

**Comment by thw1021** [comment]
@jerabaul29 
It's available in the [docker image](https://github.com/thw1021/Cylinder2DFlowControlGeneral#getting-started).

Or you can get it https://github.com/thw1021/Cylinder2DFlowControlGeneral/tree/b83b3768217f5c0997a277dc3a35e062f4126f51

**Comment by thw1021** [comment]
Let me know if there is any problem 😁

**Comment by jerabaul29** [comment]
@FabioPINO @mendezVKI this is where the trained ANN is available :) .

**Comment by mendezVKI** [comment]
Thank you very much Jean! and thank to both of you for yesterday meeting. 
I am sorry it had to end up in a rush due to meeting density.

I think we discussed very interesting points and the discussion was very fruitful. I look forward to the followup in January!

**Comment by jerabaul29** [comment]
That sounds excellent, no worries :) .
