### ISSUE TITLE
typo in Eqn. (20)

### ISSUE THREAD

**Issue by jerabaul29** [thw1021/Cylinder2DFlowControlGeneral#3]
Hi @thw1021 .

@jviquerat found a small typo in the paper. In Eqn. (20), this should be rather something like:

```
c_i=a_{j−1}+ i *(a_j−a_{j−1}) / Ne
```

or something like this, right? I.e., there is a ```i``` missing at the numerator of the fraction part, right?

This is not a big worry at all, small typos in this kind happen all the time, but would be great to mention it. Can you add on the readme of the present repo a "Typos in the paper" section, a bit like what is written at the end of the readme at https://github.com/jerabaul29/Cylinder2DFlowControlDRL , where you show the correct equation, and mention that this has always been correctly implemented in the code and is purely a typo? :) .

**Comment by jerabaul29** [comment]
And many thanks @jviquerat for reading the paper carefully, noticing the problem, and letting us know :) .

**Comment by thw1021** [comment]
Yes, I have added an explanation. Thank you @jerabaul29 @jviquerat
