### ISSUE TITLE
Why do you need power 2 of self.radius (Line57)?  Is self.radius==D/2 in your published paper Eqn.(6)?

### ISSUE THREAD

**Issue by XueminLiu111** [thw1021/Cylinder2DFlowControlGeneral#5]
https://github.com/thw1021/Cylinder2DFlowControlGeneral/blob/ac5ea7fd304dedefa4489790e45c42ca9428440e/RobustDRLCylinder2DControl/jet_bcs.py#L57

Appreciate help.

**Comment by jerabaul29** [comment]
Mmh, can you see on the Readme here, at the very end:

https://github.com/jerabaul29/Cylinder2DFlowControlDRL

I think there was some typo problems in the first paper, and this may have propagated ... :( . But if I remember well in 'dimensional units' of the code the radius is 1 or 0.5, not sure would need to check, so should not be a big difference in the end. Still annoying :( .

**Comment by XueminLiu111** [comment]
Thanks for your reply. 
I find jet_radius=0.05 in the previous settings so it may have some influence on the magnitude of jet_bcu (T_T).
https://github.com/jerabaul29/Cylinder2DFlowControlDRL/blob/44f526f45187eb63e06bea9c586e9efa6a04650d/Cylinder2DFlowControlWithRL/baseline_flow/env.py#L43

Anyway, thanks for your help.

**Comment by jerabaul29** [comment]
Mmh, yes you are right, this is another "issue / question" than what was discussed in the readme regarding equation B3, and I was confused in my answer an hour ago (also I do not remember the code too well, this is quite old, and another person wrote the BCs stuff initially), please ignore it, good you picked that up :) .

I would think this should be right, as other groups have reproduced similar results with different implementations. The choices of dimensionalizations are a bit confusing, and I will need to go through these again. I let you know.

**Comment by XueminLiu111** [comment]
Sure. Look forward to your information.
Thanks a lot!

**Comment by jerabaul29** [comment]
Sorry for the confusion... I double checked:

- this is well the same issue as reported at the end of the readme of https://github.com/jerabaul29/Cylinder2DFlowControlDRL,
- i.e., there should be no square at the end of Eqn. B3 in the JFM paper, i.e. there is a typo in the paper
- however, the code is correct. This is because, while there is a square at the denominator here:

https://github.com/thw1021/Cylinder2DFlowControlGeneral/blob/ac5ea7fd304dedefa4489790e45c42ca9428440e/RobustDRLCylinder2DControl/jet_bcs.py#L57

one of the R at the denominator is canceled by this part here:

https://github.com/thw1021/Cylinder2DFlowControlGeneral/blob/ac5ea7fd304dedefa4489790e45c42ca9428440e/RobustDRLCylinder2DControl/jet_bcs.py#L49-L50

which is NOT a unit vector in the direction perpendicular to the local cylinder tangent, but R times the unit vector perpendicular to the local cylinder tangent.

Does that make sense?

I know of at least another group that had the same question, got the same answer as I just wrote in this post, implemented in their own code in their own way, and got the same result, so this should be correct :) .

**Comment by jerabaul29** [comment]
So, sorry again, several conventions are very confusing, and there is a typo in the initial paper, but the code should be right :) .

**Comment by jerabaul29** [comment]
Triple checked, that should be the right explanation. I nearly get a heart attack each time I have to look at this again, but in the end, I think the code is right, and the error is only the typo in the initial paper as described at the end of  https://github.com/jerabaul29/Cylinder2DFlowControlDRL :)

Let me know if anything is unclear.

**Comment by XueminLiu111** [comment]
Yes, that makes sense! Thanks very much for your clear explanation!

**Comment by jerabaul29** [comment]
Glad that helped :) Good luck with your DRL projects, are you going to work specifically on DRL and Fluid Mechanics? :) .

**Comment by XueminLiu111** [comment]
Yeah. Try to do some research in these fields. And your work is really a good example to learn and start with.

**Comment by jerabaul29** [comment]
😊👌👍 Exciting, good luck :) .

One paper that I think you should have a look at too (it has received a bit less attention but I think actually that it contains important ideas and results):

https://aip.scitation.org/doi/full/10.1063/1.5132378

I think these invariance considerations are the key to getting DRL applied effectively to 3D flows.

**Comment by XueminLiu111** [comment]
Thanks for your recommendation. I'll download and have a look. (^^)
If I have more questions, I'll let you know.

**Comment by jerabaul29** [comment]
Sounds good!

If you want to have a chat some day on Zoom or similar just let me know :) .

**Comment by XueminLiu111** [comment]
Actually, I do have a question about the mesh.(^_^)
Did you use generate_mesh.py file to generate the mesh. I've never used
gmsh... Is there any tutorial you recommend to help me understand your code?
Thanks a lot (^^)

**Comment by jerabaul29** [comment]
Yes, we use gmsh, but wrapped by a Python script. Can you first have a look at section "Making a new mesh" here: https://github.com/jerabaul29/Cylinder2DFlowControlDRL and see if this helps? :) The gmsh binary in the right version should also be on the same repo.

**Comment by jerabaul29** [comment]
PS: I think gmsh is already part of the docker container used for this repo, I think it is only the old singularity container that did not have it built in :) .

**Comment by XueminLiu111** [comment]
Thanks. I'll check it out.

**Comment by thw1021** [comment]
@XueminLiu111 
gmsh in the docker container of this repo is installed by `sudo apt install gmsh`. So it is not the newest version of gmsh. And the comments in this [file](https://github.com/thw1021/Cylinder2DFlowControlGeneral/blob/master/RobustDRLCylinder2DControl/geometry_2d.template_geo) may help you.

**Comment by XueminLiu111** [comment]
Thanks very much for your help! I'll have a look.
