### ISSUE TITLE
symmetric flow simulation

### ISSUE THREAD

**Issue by YL-kl** [thw1021/Cylinder2DFlowControlGeneral#8]
Hello, many thanks for this GitHub page and for the wonderful workshop. I tried to follow your steps and figure it out, and there are some questions bother me for some days, hope to get your help.

It seems that in the second figure on the GitHub page, the Symmetric flow value (black) is higher than the controlled value (orange) when the Reynolds numbers is above 180.
![image](https://user-images.githubusercontent.com/54199730/198496525-a28fa9e4-12e8-42c5-88df-ba6dd047def7.png)

And there comes some questions:

Q1: Is this reasonable？

Q2: Which part of the code should be looked for to reproduce this simulation of symmetric flow?

Q3: Or is there any other way to get the true value of the drag without vortex shedding to be the baseline value?

Sincerely looking forward to your reply!

Best wishes~

**Comment by thw1021** [comment]
Thanks for your interest in our work. I will try to answer your questions.

> Q1: Is this reasonable？
I think it is reasonable. With the increasing Reynolds number, the flow separation could be more severe. It should be noted that there is still flow separation in symmetric flow, even though the vortex shedding is depressed. The deployed jets can delay the separation, thus achieving better effects at relatively higher Reynolds numbers.

> Q2: Which part of the code should be looked for to reproduce this simulation of symmetric flow?
I may have put this part of the code in the [docker image](https://github.com/thw1021/Cylinder2DFlowControlGeneral#getting-started). Not sure. You can also find it [here](https://github.com/jerabaul29/Cylinder2DFlowControlDRL/tree/master/symmetric_case).

> Q3: Or is there any other way to get the true value of the drag without vortex shedding to be the baseline value?
The simulation is carried out by using a symmetric boundary condition at the equatorial plane of the flow domain. You can do it with your own CFD solver.

Hope it helps.

Best regards.

**Comment by YL-kl** [comment]
您好，这里是小文同学，已收到您的邮件！

**Comment by thw1021** [comment]
Close it now. Feel free to reopen.

**Comment by YL-kl** [comment]
thanks for your reply, and please don't mind the automatic reply of the mailbox
